--df dictionary_0: word=./dictionaries/apple-permutations.txt 
 --df dictionary_1: word=./dictionaries/dictionary100.txt 
 --df dictionary_2: word=./dictionaries/dictionary101.txt 
 --df dictionary_3: word=./dictionaries/dictionary102.txt 
 --df dictionary_4: word=./dictionaries/dictionary103.txt 
 --df dictionary_5: word=./dictionaries/dictionary104.txt 
 --df dictionary_6: word=./dictionaries/dictionary105.txt 
 --df dictionary_7: word=./dictionaries/dictionary106.txt 
 --df dictionary_8: word=./dictionaries/dictionary107.txt 
 --df dictionary_9: word=./dictionaries/dictionary108.txt 
 --df dictionary_10: word=./dictionaries/dictionary109.txt 
 --df dictionary_11: word=./dictionaries/dictionary110.txt 
 --df dictionary_12: word=./dictionaries/dictionary16.txt 
 --df dictionary_13: word=./dictionaries/dictionary17.txt 
 --df dictionary_14: word=./dictionaries/dictionary18.txt 
 --df dictionary_15: word=./dictionaries/dictionary19.txt 
 --df dictionary_16: word=./dictionaries/dictionary20.txt 
 --df dictionary_17: word=./dictionaries/dictionary21.txt 
 --df dictionary_18: word=./dictionaries/dictionary22.txt 
 --df dictionary_19: word=./dictionaries/dictionary23.txt 
 --df dictionary_20: word=./dictionaries/dictionary24.txt 
 --df dictionary_21: word=./dictionaries/dictionary25.txt 
 --df dictionary_22: word=./dictionaries/dictionary26.txt 
 --df dictionary_23: word=./dictionaries/dictionary27.txt 
 --df dictionary_24: word=./dictionaries/dictionary28.txt 
 --df dictionary_25: word=./dictionaries/dictionary29.txt 
 --df dictionary_26: word=./dictionaries/dictionary30.txt 
 --df dictionary_27: word=./dictionaries/dictionary31.txt 
 --df dictionary_28: word=./dictionaries/dictionary32.txt 
 --df dictionary_29: word=./dictionaries/dictionary33.txt 
 --df dictionary_30: word=./dictionaries/dictionary34.txt 
 --df dictionary_31: word=./dictionaries/dictionary35.txt 
 --df dictionary_32: word=./dictionaries/dictionary36.txt 
 --df dictionary_33: word=./dictionaries/dictionary37.txt 
 --df dictionary_34: word=./dictionaries/dictionary38.txt 
 --df dictionary_35: word=./dictionaries/dictionary39.txt 
 --df dictionary_36: word=./dictionaries/dictionary40.txt 
 --df dictionary_37: word=./dictionaries/dictionary41.txt 
 --df dictionary_38: word=./dictionaries/dictionary42.txt 
 --df dictionary_39: word=./dictionaries/dictionary43.txt 
 --df dictionary_40: word=./dictionaries/dictionary44.txt 
 --df dictionary_41: word=./dictionaries/dictionary45.txt 
 --df dictionary_42: word=./dictionaries/dictionary46.txt 
 --df dictionary_43: word=./dictionaries/dictionary47.txt 
 --df dictionary_44: word=./dictionaries/dictionary48.txt 
 --df dictionary_45: word=./dictionaries/dictionary49.txt 
 --df dictionary_46: word=./dictionaries/dictionary50.txt 
 --df dictionary_47: word=./dictionaries/dictionary51.txt 
 --df dictionary_48: word=./dictionaries/dictionary52.txt 
 --df dictionary_49: word=./dictionaries/dictionary53.txt 
 --df dictionary_50: word=./dictionaries/dictionary54.txt 
 --df dictionary_51: word=./dictionaries/dictionary55.txt 
 --df dictionary_52: word=./dictionaries/dictionary56.txt 
 --df dictionary_53: word=./dictionaries/dictionary57.txt 
 --df dictionary_54: word=./dictionaries/dictionary58.txt 
 --df dictionary_55: word=./dictionaries/dictionary59.txt 
 --df dictionary_56: word=./dictionaries/dictionary60.txt 
 --df dictionary_57: word=./dictionaries/dictionary61.txt 
 --df dictionary_58: word=./dictionaries/dictionary62.txt 
 --df dictionary_59: word=./dictionaries/dictionary63.txt 
 --df dictionary_60: word=./dictionaries/dictionary64.txt 
 --df dictionary_61: word=./dictionaries/dictionary65.txt 
 --df dictionary_62: word=./dictionaries/dictionary66.txt 
 --df dictionary_63: word=./dictionaries/dictionary67.txt 
 --df dictionary_64: word=./dictionaries/dictionary68.txt 
 --df dictionary_65: word=./dictionaries/dictionary69.txt 
 --df dictionary_66: word=./dictionaries/dictionary70.txt 
 --df dictionary_67: word=./dictionaries/dictionary71.txt 
 --df dictionary_68: word=./dictionaries/dictionary72.txt 
 --df dictionary_69: word=./dictionaries/dictionary73.txt 
 --df dictionary_70: word=./dictionaries/dictionary74.txt 
 --df dictionary_71: word=./dictionaries/dictionary75.txt 
 --df dictionary_72: word=./dictionaries/dictionary76.txt 
 --df dictionary_73: word=./dictionaries/dictionary77.txt 
 --df dictionary_74: word=./dictionaries/dictionary78.txt 
 --df dictionary_75: word=./dictionaries/dictionary79.txt 
 --df dictionary_76: word=./dictionaries/dictionary80.txt 
 --df dictionary_77: word=./dictionaries/dictionary81.txt 
 --df dictionary_78: word=./dictionaries/dictionary82.txt 
 --df dictionary_79: word=./dictionaries/dictionary83.txt 
 --df dictionary_80: word=./dictionaries/dictionary84.txt 
 --df dictionary_81: word=./dictionaries/dictionary85.txt 
 --df dictionary_82: word=./dictionaries/dictionary86.txt 
 --df dictionary_83: word=./dictionaries/dictionary87.txt 
 --df dictionary_84: word=./dictionaries/dictionary88.txt 
 --df dictionary_85: word=./dictionaries/dictionary89.txt 
 --df dictionary_86: word=./dictionaries/dictionary90.txt 
 --df dictionary_87: word=./dictionaries/dictionary91.txt 
 --df dictionary_88: word=./dictionaries/dictionary92.txt 
 --df dictionary_89: word=./dictionaries/dictionary93.txt 
 --df dictionary_90: word=./dictionaries/dictionary94.txt 
 --df dictionary_91: word=./dictionaries/dictionary95.txt 
 --df dictionary_92: word=./dictionaries/dictionary96.txt 
 --df dictionary_93: word=./dictionaries/dictionary97.txt 
 --df dictionary_94: word=./dictionaries/dictionary98.txt 
 --df dictionary_95: word=./dictionaries/dictionary99.txt 
 --df dictionary_96: word=./dictionaries/english3.txt 
 --df dictionary_97: word=./dictionaries/italiano.txt 
 --df dictionary_98: word=./dictionaries/keywords.txt 
 --df dictionary_99: word=./dictionaries/names2017.txt 
 --df dictionary_100: word=./dictionaries/password-permutations.txt 
 --df dictionary_101: word=./dictionaries/passwords1.txt 
 --df dictionary_102: word=./dictionaries/passwords2.txt 
 --df dictionary_103: word=./dictionaries/passwords3.txt 
 --df dictionary_104: word=./dictionaries/passwords4.txt 
 --df dictionary_105: word=./dictionaries/passwords5.txt 
 --df dictionary_106: word=./dictionaries/passwords6.txt 
 --df dictionary_107: word=./dictionaries/passwords7.txt 
 --df dictionary_108: word=./dictionaries/primes-to-100k.txt 
 --df dictionary_109: word=./dictionaries/primes-to-200k.txt 
 --df dictionary_110: word=./dictionaries/words_alpha_370099.txt 
 CREATE TABLE schema_1.relation_1 ( --df: size=149 
attribute_5 text UNIQUE NOT NULL,--df: use=dictionary_56 offset=0 step=1 shift=0 size=601
attribute_0 text UNIQUE NOT NULL,--df: use=dictionary_32 offset=0 step=1 shift=0 size=601
attribute_2 text UNIQUE NOT NULL,--df: use=dictionary_107 offset=0 step=1 shift=0 size=184381
attribute_3 text UNIQUE NOT NULL,--df: use=dictionary_57 offset=0 step=1 shift=0 size=601
attribute_4 text UNIQUE NOT NULL,--df: use=dictionary_88 offset=0 step=1 shift=0 size=601
attribute_11 text UNIQUE NOT NULL--df: prefix=kh
);

CREATE TABLE schema_1.relation_2 ( --df: size=167 
attribute_6 text UNIQUE NOT NULL,--df: use=dictionary_56 offset=0 step=1 shift=0 size=601
attribute_1 text UNIQUE NOT NULL,--df: use=dictionary_2 offset=0 step=1 shift=0 size=601
attribute_7 text UNIQUE NOT NULL,--df: prefix=VJLgjca5M2
attribute_8 text UNIQUE NOT NULL,--df: prefix=NknQJNjwL0
attribute_9 text UNIQUE NOT NULL,--df: prefix=KJh8dTb4W7
attribute_10 text UNIQUE NOT NULL--df: prefix=Bi
);

